FROM nginx:1.17.4-alpine

# COPY wait.sh /wait.sh

# RUN chmod +x /wait.sh

# CMD ["/wait.sh", "web-back:3000", "--", "nginx", "-g", "daemon off;"]

RUN rm /etc/nginx/conf.d/default.conf
COPY default.dev.conf /etc/nginx/conf.d
